name: CD
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./node_modules/.cache
          key: ${{ runner.os }}-nodemodules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
